fix: manually cast the Error to string (#469)
I got an error using hooks incorrectly, but all I saw was
```
invalid argument #4 to 'format' (string expected, got table)
------ Error caught by React ------
ReplicatedStorage.Packages._Index.ReactRoblox.ReactRoblox.client.roblox.RobloxComponentProps:242 function setInitialProperties
ReplicatedStorage.Packages._Index.ReactRoblox.ReactRoblox.client.ReactRobloxHostConfig:407
```
It's because hooks error is an Error object from Polyfill and tostring
is not called by format (no idea why)

Now the errors look like
```
Error applying initial props to Roblox Instance 'SizeConstraint' (UISizeConstraint):
  Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

Checklist before submitting:
* [ ] Added/updated relevant tests
* [ ] Added/updated documentation

---------